name: API and Web Automation Workflow


# EVENT
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Manually running a workflow  
  workflow_dispatch:

jobs:
  build:
    # Running on Virtual machine
    runs-on: ubuntu-latest


    steps:
    # download repo
    - uses: actions/checkout@v4

    # set up java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    #set up gradlew
    - name: Setup gradlew
      run: chmod +x gradlew
      
    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew webTest || true
      
    - name: Execute Test
      run: ./gradlew apiTest || true
      
    # || true:  Operator logika ini memastikan bahwa jika perintah di sebelah kiri gagal (mengembalikan status kode bukan nol)
    #           perintah di sebelah kanan (true) akan dieksekusi, yang selalu berhasil. Dengan demikian, status keseluruhan dari perintah akan dianggap berhasil. 
    #           Ini berguna dalam konteks CI untuk menghindari penghentian pipeline karena kegagalan tes sementara.


    # # Upload Artifact Report
    # - name: Archive Test Result
    #   uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: Cucumber Report
    #     path: reports


